### ISSUE TITLE
www-client/ungoogled-chromium-81.0.4044.129_p1 fails to build with dev-libs/icu-67.1

### ISSUE THREAD

**Issue by crabbedhaloablution** [PF4Public/gentoo-overlay#33]
[629/893] x86_64-pc-linux-gnu-clang++ -MMD -MF obj/v8/v8_base_without_compiler/js-number-format.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE>
^[[31mFAILED: ^[[0mobj/v8/v8_base_without_compiler/js-number-format.o
x86_64-pc-linux-gnu-clang++ -MMD -MF obj/v8/v8_base_without_compiler/js-number-format.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLAN>
^[[1m../../v8/src/objects/js-number-format.cc:1227:15: ^[[0m^[[0;1;31merror: ^[[0m^[[1mno member named 'getAllFieldPositions' in 'icu::number::FormattedNumber'^[[0m
    formatted.getAllFieldPositions(*fp_iter, status);
^[[0;1;32m    ~~~~~~~~~ ^
^[[0m1 error generated.

[build.log](https://github.com/PF4Public/gentoo-overlay/files/4571518/build.log)

**Comment by PF4Public** [comment]
Looks like newer version of icu got incompatible with chromium. A patch is needed.
In a meanwhile as a temporary workaround one could compile without `system-icu` or with older version of icu.

**Comment by PF4Public** [comment]
I have added necessary patches. Please, test whether this is sufficient.
Feel free to close the issue, if it is solved.

**Comment by crabbedhaloablution** [comment]
Builds and runs. Thanks a lot👍
