### ISSUE TITLE
www-client/ungoogled-chromium-114.0.5735.198_p1: breaks with system-ffmpeg enabled with ffmpeg-4.4.4

### ISSUE THREAD

**Issue by logrusx** [PF4Public/gentoo-overlay#243]
ffmpeg changed ABI in 4.4.4 and chromium fails to build with a bunch of:

```../../media/ffmpeg/ffmpeg_common.cc:390:22: error: no member named 'ch_layout' in 'AVCodecContext'
      codec_context->ch_layout.nb_channels > 8
      ~~~~~~~~~~~~~  ^
../../media/ffmpeg/ffmpeg_common.c
```
The upstream bug is [https://bugs.chromium.org/p/chromium/issues/detail?id=1325301](url)

I've fixed the patch in that bug and it built successfully for me with it.

Unfortunately I don't know how to do the neseccary check for ffmpeg version in the ebuild and this cannot submit a pull request. Here is the patch:

[chromium-114-ffmpeg-4.4.4.patch.zip](https://github.com/PF4Public/gentoo-overlay/files/11949108/chromium-114-ffmpeg-4.4.4.patch.zip)

An alternative solution is to remove the system-ffmpeg use flag. Original chromium ebuild from the main tree has masked it.

Best Regards,
Georgi

**Comment by PF4Public** [comment]
Full error message please.

**Comment by logrusx** [comment]
Sorry for missing error message, I rushed into fixing the patch and forgot to gather the relevant logs.
I already built it and generated the patch from that build tree, but if you want me to test-build, just confirm and I can do it overnight, will have the results in ~15 hours or so.

Best Regards,
Georgi

**Comment by PF4Public** [comment]
>but if you want me to test-build, just confirm and I can do it overnight, will have the results in ~15 hours or so.

That'd be great.


> this way it wouldn't build with versions less than 4.4.4. Not that they are going to stay much longer in the tree, after 4.4.4 has been stabilized, but...

You are correct and I hope people will soon update to 4.4.4 and there will be no problem applying those patches.

**Comment by logrusx** [comment]
Compiled successfully.
