### ISSUE TITLE
dev-util/electron-42.5.0: doesn't compile with dev-lang/rust-1.95.0 cannot find type `LaneCount` in module `core::simd`

### ISSUE THREAD

**Issue by F3llFr0mTh3Sky** [PF4Public/gentoo-overlay#514]
See the logs:
[2026-07-03_electron_42.5.0_build.log.gz](https://github.com/user-attachments/files/29649569/2026-07-03_electron_42.5.0_build.log.gz)

<img width="1920" height="225" alt="Image" src="https://github.com/user-attachments/assets/0ac74e7f-9c42-46d5-941f-ce9bda15aeb6" />

Relevant part of the logs:
<img width="1661" height="725" alt="Image" src="https://github.com/user-attachments/assets/f2c40963-00d2-4957-8591-548cfd88fd8c" />

**Comment by F3llFr0mTh3Sky** [comment]
Just noticed someone already reported the same issue here:
https://github.com/PF4Public/gentoo-overlay/issues/496

**Comment by F3llFr0mTh3Sky** [comment]
Acutally, woops, actually maybe it should be reopened, but your choice. (yes I did read correctly what you said in https://github.com/PF4Public/gentoo-overlay/issues/496). And I did tested the patch linked in https://github.com/PF4Public/gentoo-overlay/pull/511 too, it's working.

**Comment by PF4Public** [comment]
That's a good point, thanks!
